all_test_data:
- test_data: product_SKU110K
  test_split: test
  yolo_predict_session_param:
    test_input_size: 928
- test_data: product_SKU110K
  test_split: trainval
  yolo_predict_session_param:
    test_input_size: 928
- test_data: product_SKU110K
  test_split: test
  yolo_predict_session_param:
    test_input_size: 800
- test_data: product_SKU110K
  test_split: trainval
  yolo_predict_session_param:
    test_input_size: 800
- test_data: product_SKU110K
  test_split: test
  yolo_predict_session_param:
    test_input_size: 1056
- test_data: product_SKU110K
  test_split: trainval
  yolo_predict_session_param:
    test_input_size: 1056
param:
  basemodel: ./output/Tax1300V14.4_0.0_0.0_darknet19_448_C_Init.best_model6933_maxIter.10eEffectBatchSize128LR7580_bb_only_yolov2pt/snapshot/model_iter_139900.pt
  data: product_SKU110K
  dist_url_tcp_port: 29144
  effective_batch_size: 128
  expid: YoloV2Pt2_basemodel1876a_BS128_MaxIter20e_ExtraConv2_AugTrials50_ScaleMin1.2_ScaleMax3.2_MaskSam
  expid_prefix: YoloV2Pt2
  max_iter: 20e
  net: darknet19_448
  num_extra_convs: 2
  pipeline_type: YoloV2PtPipeline
  use_treestructure: false
  yolo_predict_session_param:
    test_input_size: 416
  yolo_train_session_param:
    data_augmentation:
      box_data_param:
        max_trials: 50
        random_scale_max: 3.2
        random_scale_min: 1.2
    use_maskrcnn_sampler: true
type: pipeline_train_eval_multi
