vc: input
cluster: wu1
user_name: jianfw
password: YourPassword
blob_mount_point: /blob
config_param:
    # please make sure each path starts with blob_mount_point
    code_path: /blob/YourAlias/code/quickdetection.zip
    data_folder: /blob/jianfw/data/qd_data
    model_folder: /blob/jianfw/work/qd_models
    output_folder: /blob/jianfw/work/qd_output
docker:
    image: philly/jobs/test/vig-qd-env
    tag: py27pt1
    #tag = 'v1.0'
    #tag = 'py36pt1'
    #tag = 'py3pt3'
